runner:
  total_steps: 400000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 10
  eval_step: 4000
  save_step: 2000
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
        #name: TorchOptim
        #torch_optim_name: Adam
  name: AdamW
  lr: 3.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 2000

downstream_expert:
  datarc:
    vggsound_root: "/work/u3933430/VGGSound/VGGSound"
    train_location: "/work/u3933430/vggaudiosetdl/vggsound/vggsound_train.csv"
    val_location: "/work/u3933430/vggaudiosetdl/vggsound/vggsound_dev.csv"
    test_location: "/work/u3933430/vggaudiosetdl/vggsound/vggsound_test.csv"
    num_workers: 4
    train_batch_size: 16
    eval_batch_size: 16


  modelrc:
    output_num_class: 310
    device: cuda
    input_dim: 512
    hidden_dim: 256
    hidden_layers: 3


