runner:
  total_steps: 20000
  gradient_clipping: 1
  gradient_accumulate_steps: 2

  log_step: 50
  eval_step: 500
  save_step: 500
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1400

downstream_expert:
  datarc:
    num_workers: 2
    train_batch_size: 2
    eval_batch_size: 2
    lrs_version: 3 # choices are 2 (BBC) or 3 (TED)

  modelrc:
    input_dim: 256
    upsample_rate: 1
    dropout_rate: .2
