runner:
  total_steps: 20000
  gradient_clipping: 1
  gradient_accumulate_steps: 2

  log_step: 10
  eval_step: 20
  save_step: 20
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1400

downstream_expert:
  datarc:
    vggsound_root: "/home/u3933430/vggaudiosetdl/vggsound"
    train_location: "/home/u3933430/vggaudiosetdl/vggsound/vggsound_train.csv"
    val_location: "/home/u3933430/vggaudiosetdl/vggsound/vggsound_dev.csv"
    test_location: "/home/u3933430/vggaudiosetdl/vggsound/vggsound_test.csv"
    num_workers: 12
    train_batch_size: 2
    eval_batch_size: 2

  modelrc:
    input_dim: 256