runner:
  gradient_clipping: 1
  gradient_accumulate_steps: 64

  total_steps: 5000
  log_step: 25
  eval_step: 500
  save_step: 200
  max_keep: 1
  eval_dataloaders:
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-2

downstream_expert:
  datarc:
    vggsound_root:      "/work/u2707828/VGGSound/VGGSound"
    feature_root:       "/work/u2707828/features"
    train_location:     "./split/split/vggsound_train.csv"
    val_location:       "./split/split/vggsound_dev.csv"
    test_location:      "./split/split/vggsound_test.csv"
    save_features:      False
    class_num: 310 
    num_workers: 16
    train_batch_size: 2
    eval_batch_size: 2

  modelrc:
    device: cuda
    input_dim: 256

