runner:
  gradient_clipping: 1
  gradient_accumulate_steps: 64

  total_steps: 5000
  log_step: 25
  eval_step: 500
  save_step: 50
  max_keep: 1
  eval_dataloaders:
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-5

downstream_expert:
  datarc:
    vggsound_root:      "/work/u2707828/VGGSound/VGGSound_test"   #"VGGSOUND_DATA_PATH"
    feature_root:       "/work/u2707828/testdata" #"PAVE_TO_SAVE_FEATURE"
    train_location:     "./downstream_tasks/vggsound/split/split/vggsound_train.csv"
    val_location:       "./downstream_tasks/vggsound/split/split/vggsound_dev.csv"
    test_location:      "./downstream_tasks/vggsound/split/split/vggsound_test.csv"
    save_features:      False
    class_num: 310 
    num_workers: 4
    train_batch_size: 2
    eval_batch_size: 2

  modelrc:
    device: cuda
    input_dim: 256

