runner:
  total_steps: 5000
  gradient_clipping: 1
  gradient_accumulate_steps: 64

  log_step: 25
  eval_step: 5000
  save_step: 200
  max_keep: 1
  eval_dataloaders:
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
#scheduler:
# name: linear_schedule_with_warmup
# num_warmup_steps: 20000

downstream_expert:
  datarc:
    vggsound_root:      "/work/u2707828/VGGSound/VGGSound"
    feature_root:       "/work/u2707828/features"
    train_location:     "./split/split/vggsound_train.csv"
    val_location:       "./split/split/vggsound_dev.csv"
    test_location:      "./split/split/vggsound_test.csv"
    save_features:      True
    class_num: 310 
    num_workers: 16
    train_batch_size: 2
    eval_batch_size: 2


  modelrc:
    device: cuda
    input_dim: 256




    #hidden_dim: 256
    #hidden_layers: 2
    #dropout: 0.3
    #batchnorm: True


