name: python

# Trigger the workflow on push or pull request
on: [push, pull_request]

# env:

jobs:
  check-style:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip  
          pip install -r ./dev-support/lint-requirements.txt
      - name: Check python code style
        run: ./dev-support/lint.sh
